config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


get '/' => "main#index"
get '/contacts' => "main#contacts"
get '/terminal' => "main#terminal"


resources :main
resources :posts
resources :albums do
  resources :pics
end
resources :events

end

app/models/album.rb
class Album < ApplicationRecord
  has_many :pics

  validates :title, presence: { :message => "Выберите название альбома!!!"} 
  validates :title, :length => { :maximum => 20, :message => "Слишком длинное название альбома!!!"} 
  validates :author, presence: true
  
  validates :image, presence: {:message => "Выберите обложку альбома!!!"}
  validates_format_of :image,  :with => %r{(png|jpg|jpeg)}i, :message => "Неправильный формат файла !!"

  mount_uploader :image, AlbumimgUploader
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/event.rb
class Event < ApplicationRecord

  validates :title, presence: {:message => "Тема встречи не указана!!"}
  validates :title, :length => {:maximum => 20, :message => "Слишком длинная тема встречи !!"} 
  validates :author, presence: true
  validates :content, presence: {:message => "Опишите событие!!"}
  validates :content, :length => {:maximum => 2000, :message => "Слишком много текста!!"}
  validates :date, presence: {:message => "Выберите дату!!"}
  validates :image, presence: {:message => "Выберите обложку встречи!!"}


mount_uploader :image, EventimageUploader
  
end

app/models/pic.rb
class Pic < ApplicationRecord
belongs_to :album

mount_uploaders :images, PicimageUploader
serialize :images, JSON # If you use SQLite, add this line.


  
validates :images, presence: {:message => "Вы не выбрали ни одну фотографию!!"}

validates_format_of :images,  :with => %r{(png|jpg|jpeg)}i, :message => "Неправильный формат файла !!"


end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: {:message => "Выберите тему поста!!"}
  validates :title, :length => { :maximum => 40, :message => "Слишком длинная тема поста !!"}
  validates :author, presence: true
  validates :content, presence: {:message => "Напишите текст поста!!"}

  validates :image, presence:  {:message => "Посту нужна обложка!!"}
  validates_format_of :image,  :with => %r{(png|jpg|jpeg)}i, :message => "Неправильный формат файла !!"

  mount_uploader :image, PostimageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true
  validates :email, uniqueness: true
  validates :username, presence: true
  validates :username, uniqueness: true
       
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController




def index

@bckg = "/img/home.jpg"
@title = "Галерея"
@label = "нашего клуба"


@albums=Album.all
@tab_title = "Галерея"
end


def new

@album = Album.new

@bckg = "/img/home.jpg"
@title = "Галерея"
@label = "Храма свв. бесср. Космы и Дамиана"

end



def create
@bckg = "home.jpg"
@title = "Галерея"
@label = "Храма свв. бесср. Космы и Дамиана"


@album = Album.new(album_params)
      
      if  @album.save
        redirect_to @album
      else
        render action: 'new'
      end
  end


def show



@album = Album.find(params[:id])

@bckg = @album.image

@title = @album.title

@label = @album.content
  
@tab_title = @album.title 

end



def destroy
  @album = Album.find(params[:id])
  
  @album.comments.each do |comment|
    comment.destroy
  end

  

  @album.destroy


  redirect_to albums_path

end




def album_params
    params.require(:album).permit(:author, :content, :title, :image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?
#before_action :authenticate_user!


protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController


$rusdate = %w[0 января февраля марта апреля мая июня июля августа сентября октября ноября декабря ]


def index
  @events = Event.order(:date)



   
  @bckg = "/img/home.jpg"
  @title = "Встречи"
  @label = "Храма свв. бесср. Космы и Дамиана"
  @tab_title = "События"

end




    def new
      @event = Event.new
      @bckg = "/img/home.jpg"
      @title = "Новое событие"
      @label = ""
    end

    def create

      @event = Event.new(event_params)
        
        if  @event.save
          redirect_to @event
        else
          render action: 'new'
        end
    end

  def show
    @event = Event.find(params[:id])


    @bckg = @event.image

    @title = @event.title

    @label =""

    @tab_title = @event.title

  end

def destroy
  @event = Event.find(params[:id])
  
  #@post.comments.each do |comment|
  #  comment.destroy
  #end


  @event.destroy


  redirect_to events_path

end

def event_params
    params.require(:event).permit(:author, :content, :title, :image, :date)
  end


end

app/controllers/main_controller.rb
class MainController < ApplicationController
$rusdate = %w[0 января февраля марта апреля мая июня июля августа сентября октября ноября декабря ]

def index


@posts = Post.all.last(5)
@events = Event.order(:date).last(5)
@albums = Album.all.last(5)
@label = "и другие интересные функции"
@album = Pic.all.last(10)
@tab_title = "Главная"


  @bckg = "/img/home.jpg"
  @title = "Главная"
  @label = "Добро пожаловать на сайт Приходского Молодежно-подросткового Клуба 
Храма свв. бесср. Космы и Дамиана (в Шубине)!
"
end

def terminal

@users = User.all

@bckg = "/img/home.jpg"
@title = "Управление доступом"
@label = "и другие интересные функции"

end



end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

def index
end

def new

@album = Album.find(params[:album_id])

  @bckg = "/img/home.jpg"
  @title = "Загрузить новые фотографии"
  @label = ""
end

def create
    

    @album = Album.find(params[:album_id])
    @album.pics.create(pic_params)

    redirect_to album_path(@album)
 

end

def show

end

  def pic_params
    params.require(:pic).permit({images: []})
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
def authentificate
  before_action :authenticate_user!
end

def index
  @posts = Post.all

  @tab_title = "Посты"
  @bckg = "/img/home.jpg"
  @title = "Блог клуба"
  @label = "Храма свв. бесср. Космы и Дамиана"
end


def show
@post = Post.find(params[:id])



@tab_title = @post.title
@bckg = @post.image

@title = @post.title

@label =""

end


def new
@post = Post.new

  @tab_title = "Новый пост"
  @bckg = "/img/home.jpg"
  @title = "Новый пост"
  @label = ""
end

def create

    @post = Post.new(post_params)
      
      if  @post.save
        redirect_to @post
      else
        render action: 'new'
      end
  end


  def destroy
  @post = Post.find(params[:id])
  
  #@post.comments.each do |comment|
  #  comment.destroy
  #end


  @post.destroy


  redirect_to posts_path

end


  def post_params
    params.require(:post).permit(:author, :content, :title, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<%if user_signed_in?%>

            <a class="btn btn-success float-left" href=<%=new_album_url%>> Создать новый альбом </a><br/><br/><br/><br/>
        
          
          
          </div>




<%end%>


<div class="container">



    <div class="row">

    	<% @albums.reverse_each  do |album|%>
       <div  class="col-md-4 col-sm-4 col-xs-6" >


 

<div class="polaroid">
       	<a href = <%=album_url(album.id)%>>
        <p2> <%=album.title%></p2>|
       	
        <img class="img-responsive" src= <%=album.image%> />
        <p2> <%=album.author%></p2>
        <p2> <%=album.created_at%></p2></a>
    	</div> 
 </div>       







	<%end%>

	</div>

</div>

app/views/albums/new.html.erb
<div class="mx-auto" style="width: 500px;">

<%= form_for :album, url: albums_path do |f| %> 

 <% if @album.errors.any? %>
            <div id="errorExplanation">
            	 
                <ul>
                    <% @album.errors.messages.each do |msg| %>
				<div class="alert alert-danger">
                    <li><%= msg[1][0] %></li>
               	</div>
                    <% end %>
                  </ul>
             
            </div>
  <% end %>
  <p4> Создать новый альбом: </p4>

	<h1> <%= f.hidden_field  :author, value: current_user.username %> </h1>
	<t2> <%= f.label :Название_альбома %> </t2><br/>
	<p1> <%= f.text_area  :title, size: "50x1"  %> </p1><br/>

	<t2> <%= f.label :Описание_альбома %> </t2><br/>
	<p1> <%= f.text_area  :content, size: "80x10" %> </p1><br/>


	<t2><%= f.label :Обложка_альбома %></t2>
    <p1><%= f.file_field :image %></p1><br/>

	<button class="btn btn-primary" type="submit">Создать альбом</button>
 <%end%>
</div>

app/views/albums/show.html.erb
 

<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Full-featured Image Viewer/Gallery Plugin Example</title>
    <link href="/css/lightgallery.css" rel="stylesheet">
    </head>
    <body>
        <h1>Фото</h1>
        <div class="jquery-script-ads" style="margin:30px auto"><script type="text/javascript">
</script>



	<%if user_signed_in?%>
        <% if @album.errors.any? %>
            <div id="errorExplanation">
                 
                <ul>
                    <% @album.errors.messages.each do |msg| %>
                <div class="alert alert-danger">
                    <li><%= msg[1][0] %></li>
                </div>
                    <% end %>
                  </ul>
             
            </div>
    <% end %>
				  <p2><%= form_for ([@album, @album.pics.build]) do |f| %></p2>
				 <button  class = "btn btn-outline-primary" >
        				  	<p3>Добавить фотографии</p3></a><br/>
                    </button>
                            <%= f.hidden_field  :pic, value: current_user.username %> </h1>


        				  <button  class = "btn btn-outline-primary" ><%= f.file_field :images, multiple: true %></button>
        				   <button class="btn btn-outline-primary" type="submit">Сохранить</button>
	 			<%end%>
	 		
		
	<%end%>







</div>

        <div class="gallery">
            <ul id="lightgallery" class="list-unstyled row">

            	<%@album.pics.each do |pic|%>

            		<%pic.images.each do |p|%>
            	
                <li st class="col-xs-6 col-sm-3 col-md-3 "  data-responsive="<%=p%>" data-src="<%=p%>" data-sub-html="Комментарий к фотографии">
                    <a href="">
                        <div class="polaroid">
                        <img class="img-responsive" src="<%=p%>">
                        <div class="container"></div>
                    </div>
                    </a>
                  </li>
                   
                    <%end%>
                <%end%>

            </ul>
        </div>



        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>
        <script type="text/javascript">
        $(document).ready(function(){
            $('#lightgallery').lightGallery();
        });
        </script>
        <script src="/js/lightgallery-all.min.js"></script>
    </body>

    <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36251023-1']);
  _gaq.push(['_setDomainName', 'jqueryscript.net']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</html>

app/views/events/index.html.erb
<!-- Main Content -->

<div class="clearfix">
            <%if user_signed_in?%>
            <a class="btn btn-success pull-left" href=<%=new_event_url%>> Новое событие </a>
            <%end%>
          </div>
<div class="container">
      <div class="row">
        <%@events.each do |event|%>

        <div class="col-lg-12 col-md-12">
          
          <div class="event-preview">
            
            <a href=<%=event_url(event)%>>
            
              
                    <h2 class="event-title">
                    
                    <%=event.date.strftime("%d")%>-го <%=$rusdate[event.date.strftime("%m").to_i]%> <%=event.date.strftime("%Y")%> г.</
                      </h2>
                        <h2 class="event-title">
                        <%=event.title%>
                        <br/><br/>
                      </h2>
                   </div> 

                 </div>

                   <div class="col-lg-8 col-md-8 mx-auto"> 

                      
                      <img class="img-responsive mx-auto"  src= <%=event.image%> />
                 
                    </div>

                     <div class="col-lg-12 col-md-12"> 
                          
                            <h4 class="text-left">
                              <%=event.content.first(600).html_safe+"..."%>
                            </h4>

                            <div class="pull-right">
                          <button type="button"  class="btn btn-outline-primary"> читать далее...</button>
                         </div> 
                        </a>
                        <p class="post-meta pull-left">Написал
                          <a href="#"><%=event.author%></a>
                          <%=event.created_at%></p>


                          </a>
                          <hr/>
                    </div>
                  </div>
            </a>
          <hr>
          <%end%>
                 
          <!-- Pager -->
          
        </div>
      </div>
    </div>

    <hr>

app/views/events/new.html.erb
<div id="event">
	<div>
	
<t4> Создать событие: </t4>

<%= form_for :event, url: events_path do |f| %> 

 <% if @event.errors.any? %>
            <div id="errorExplanation">
            	 
                <ul>
                    <% @event.errors.messages.each do |msg| %>
				<div class="alert alert-danger">
                    <li><%= msg[1][0] %></li>
               	</div>
                    <% end %>
                  </ul>
             
            </div>
  <% end %>
	
	<h1> <%= f.hidden_field  :author, value: current_user.username %> </h1>

	<t2> <%= f.label :Название_события %> </t2><br/>
	<p1> <%= f.text_area  :title, size: "50x1", value: @event.title  %> </p1><br/>

	<t2> <%= f.label :Дата_встречи %> </t2><br/>
	<p1> <%= f.date_field  :date,  size: "40x1"  %> </p1><br/>

	<t2> <%= f.label :Описание_события %> </t2>
	<textarea  name="event[content]" >

		<%= @event.content %>
		
	
	</textarea><br/>


	<t2><%= f.label :Обложка_события %></t2>
    <p1><%= f.file_field :image %></p1><br/>

	<button class="btn btn-primary" type="submit">Создать</button>
 <%end%>

</div>
</div>

  <script>
      CKEDITOR.replace( 'event[content]');
  </script>

app/views/events/show.html.erb
<!-- event Content -->
    <article>
      <div class="container">
        <div class="row">
          <div class="col-lg-10 col-md-12 mx-auto">
            <p><%@m=@event.date.strftime("%m").to_i%></p>
           <h2 class="event-title">
            
            <%=@event.date.strftime("%d")%>-го <%=$rusdate[@event.date.strftime("%m").to_i]%> <%=@event.date.strftime("%Y")%> г.</
              </h2>
            <h4 class="text-left"><%=@event.content.html_safe%></h4>
            
            <small><%= link_to "Удалить", event_path(@event.id), method: :delete, data: {confirm: "Точно удалить?"} %>  <br/></small>
           
          </div>
        </div>
      </div>
    </article>

app/views/posts/index.html.erb
<!-- Main Content -->

          <div class="clearfix">
            <%if user_signed_in?%>
            <a class="btn btn-success float-left" href=<%=new_post_url%>>&larr; Новый пост </a>
            <%end%>
          </div>

    <div class="container">
      <div class="row">

        <div class="col-lg-10 col-md-10 mx-auto">
          <%@posts.each do |post|%>
          <div class="post-preview">

            <a href=<%=post_url(post)%>>

              <h2 class="post-title">
                <%=post.title%>
              </h2>
              
             <h4 class="text-left">
                <%=simple_format(post.content.first(300)+"...")%>
             </h4>
           
              <button type="button"  class="btn btn-outline-primary pull-right"> читать далее...</button>
            </a>
            <p class="post-meta pull-left">Написал
              <a href="#"><%=post.author%></a>
              <%=post.created_at%></p>
          </div>
          <hr/><br/>
          <%end%>
                 
          <!-- Pager -->

        </div>
      </div>
    </div>

    <hr>

    

app/views/posts/new.html.erb
		
		


<div id="post">
	<div>
		




<%= form_for :post,  url: posts_path do |f| %> 



 <% if @post.errors.any? %>
            <div id="errorExplanation">
            	 
                <ul>
                    <% @post.errors.messages.each do |msg| %>
				<div class="alert alert-danger">
                    <li><%= msg[1][0]%></li>
               	</div>
                    <% end %>
                  </ul>
             
            </div>
  <% end %>
	<t4> Написать новый пост: </t4>
	<h1> <%= f.hidden_field  :author, value: current_user.username %> </h1>

	<t2> <%= f.label :Тема_поста %> </t2><br/>
	<p1> <%= f.text_field  :title, size: "50x1", value: @post.title  %> </p1><br/>

	<t2><%= f.label :Текст_поста %> </t2><br/>
	<textarea  name="post[content]"> <%= @post.content%>
	</textarea>
	<br/>


	<t2><%= f.label :Обложка_поста %></t2>
    <p1><%= f.file_field :image %></p1><br/>

	<button class="btn btn-primary" type="submit">Создать пост</button>
 <%end%>

</div>
</div>

  <script>
      CKEDITOR.replace( 'post[content]');
      
      
  </script>

app/views/posts/show.html.erb
<!-- Post Content -->



    <article>
      <div class="container">
        <div class="row">
          <div class="col-lg-10 col-md-12 mx-auto">
          	
            

            <h4 class="text-left">
              <%=@post.content.html_safe%></h4><br/>
        
              

             <small><%= link_to "Удалить", post_path(@post.id), method: :delete, data: {confirm: "Точно удалить?"} %>  <br/></small>
          </div>
        </div>
      </div>
    </article>

app/views/users/profile.html.erb
<h1>Users#profile</h1>
<p>Find me in app/views/users/profile.html.erb</p>