config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


get '/' => "main#index"
get '/contacts' => "main#contacts"
get '/terminal' => "main#terminal"


resources :main
resources :posts
resources :albums do
  resources :pics
end
resources :events

end

app/models/album.rb
class Album < ApplicationRecord
  has_many :pics

  validates :title, presence: { :message => "Выберите название альбома!!!"} 
  validates :title, :length => { :maximum => 20, :message => "Слишком длинное название альбома!!!"} 
  validates :author, presence: true
  
  validates :image, presence: {:message => "Выберите обложку альбома!!!"}
  validates_format_of :image,  :with => %r{(png|jpg|jpeg)}i, :message => "Неправильный формат файла !!"

  mount_uploader :image, AlbumimgUploader
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  validates :title, presence: {:message => "Тема встречи не указана!!"}
  validates :title, :length => {:maximum => 20, :message => "Слишком длинная тема встречи !!"} 
  validates :author, presence: true
  validates :content, presence: {:message => "Опишите событие!!"}
  validates :content, :length => {:maximum => 2000, :message => "Слишком много текста!!"}
  validates :date, presence: {:message => "Выберите дату!!"}
  validates :image, presence: {:message => "Выберите обложку встречи!!"}


mount_uploader :image, EventimageUploader
  
end

app/models/pic.rb
class Pic < ApplicationRecord
belongs_to :album

mount_uploaders :images, PicimageUploader
serialize :images, JSON # If you use SQLite, add this line.


  
validates :images, presence: {:message => "Вы не выбрали ни одну фотографию!!"}

validates_format_of :images,  :with => %r{(png|jpg|jpeg)}i, :message => "Неправильный формат файла !!"


end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: {:message => "Выберите тему поста!!"}
  validates :title, :length => { :maximum => 40, :message => "Слишком длинная тема поста !!"}
  validates :author, presence: true
  validates :content, presence: {:message => "Напишите текст поста!!"}

  validates :image, presence:  {:message => "Посту нужна обложка!!"}
  validates_format_of :image,  :with => %r{(png|jpg|jpeg)}i, :message => "Неправильный формат файла !!"

  mount_uploader :image, PostimageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true
  validates :email, uniqueness: true
  validates :username, presence: true
  validates :username, uniqueness: true
       
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController




def index

@bckg = "/img/home.jpg"
@title = "Галерея"
@label = "нашего клуба"


@albums=Album.all
@tab_title = "Галерея"
end


def new

@album = Album.new

@bckg = "/img/home.jpg"
@title = "Галерея"
@label = "Храма свв. бесср. Космы и Дамиана"

end



def create
@bckg = "home.jpg"
@title = "Галерея"
@label = "Храма свв. бесср. Космы и Дамиана"


@album = Album.new(album_params)
      
      if  @album.save
        redirect_to @album
      else
        render action: 'new'
      end
  end


def show



@album = Album.find(params[:id])

@bckg = @album.image

@title = @album.title

@label = @album.content
  
@tab_title = @album.title 

end



def destroy
  @album = Album.find(params[:id])
  
  @album.comments.each do |comment|
    comment.destroy
  end

  

  @album.destroy


  redirect_to albums_path

end




def album_params
    params.require(:album).permit(:author, :content, :title, :image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?
#before_action :authenticate_user!


protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController


$rusdate = %w[0 января февраля марта апреля мая июня июля августа сентября октября ноября декабря ]


def index
  @events = Event.order(:date)



   
  @bckg = "/img/home.jpg"
  @title = "Встречи"
  @label = "Храма свв. бесср. Космы и Дамиана"
  @tab_title = "События"

end




    def new
      @event = Event.new
      @bckg = "/img/home.jpg"
      @title = "Новое событие"
      @label = ""
    end

    def create

      @event = Event.new(event_params)
        
        if  @event.save
          redirect_to @event
        else
          render action: 'new'
        end
    end

  def show
    @event = Event.find(params[:id])


    @bckg = @event.image

    @title = @event.title

    @label =""

    @tab_title = @event.title

  end

def destroy
  @event = Event.find(params[:id])
  
  #@post.comments.each do |comment|
  #  comment.destroy
  #end


  @event.destroy


  redirect_to events_path

end

def event_params
    params.require(:event).permit(:author, :content, :title, :image, :date)
  end


end

app/controllers/main_controller.rb
class MainController < ApplicationController
$rusdate = %w[0 января февраля марта апреля мая июня июля августа сентября октября ноября декабря ]

def index


@posts = Post.all.last(5)
@events = Event.order(:date).last(5)
@albums = Album.all.last(5)
@label = "и другие интересные функции"
@album = Pic.all.last(10)
@tab_title = "Главная"


  @bckg = "/img/home.jpg"
  @title = "Главная"
  @label = "Добро пожаловать на сайт Приходского Молодежно-подросткового Клуба 
Храма свв. бесср. Космы и Дамиана (в Шубине)!
"
end

def terminal

@users = User.all

@bckg = "/img/home.jpg"
@title = "Управление доступом"
@label = "и другие интересные функции"

end



end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

def index
end

def new

@album = Album.find(params[:album_id])

  @bckg = "/img/home.jpg"
  @title = "Загрузить новые фотографии"
  @label = ""
end

def create
    

    @album = Album.find(params[:album_id])
    @album.pics.create(pic_params)

    redirect_to album_path(@album)
 

end

def show

end

  def pic_params
    params.require(:pic).permit({images: []})
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
def authentificate
  before_action :authenticate_user!
end

def index
  @posts = Post.all

  @tab_title = "Посты"
  @bckg = "/img/home.jpg"
  @title = "Блог клуба"
  @label = "Храма свв. бесср. Космы и Дамиана"
end


def show
@post = Post.find(params[:id])



@tab_title = @post.title
@bckg = @post.image

@title = @post.title

@label =""

end


def new
@post = Post.new

  @tab_title = "Новый пост"
  @bckg = "/img/home.jpg"
  @title = "Новый пост"
  @label = ""
end

def create

    @post = Post.new(post_params)
      
      if  @post.save
        redirect_to @post
      else
        render action: 'new'
      end
  end


  def destroy
  @post = Post.find(params[:id])
  
  #@post.comments.each do |comment|
  #  comment.destroy
  #end


  @post.destroy


  redirect_to posts_path

end


  def post_params
    params.require(:post).permit(:author, :content, :title, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
    <title><%=@tab_title%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>



     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">



<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
 

<!--CleanBlog-->

 


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    

    <!-- Bootstrap core CSS -->
    <link href="/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="/css/clean-blog.css" rel="stylesheet">
    
    <!-- Gallery -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>




    <link href="/css/lightgallery.css" rel="stylesheet">
   

    <!--tabs-->
   <link href="/css/tabs.css" rel="stylesheet">
  

  <!--polaroid pics -->


<link href="/css/polaroid.css" rel="stylesheet">



 

 
  


 


<!-- Navigation -->




  <div class="container">
    <div class="row">
        
        <!--visible md-->
        <div class="hidden-xs col-sm-6 col-md-12" align="center">
          <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div  class="container">
         <ul class="navbar-nav ml-auto ">
       </ul>
        <ul class="navbar-nav ml-auto ">
        <ul class="nav justify-content-end">
        
        <li class="nav-item">

            </li>

       
              <a class="navbar-brand" href="/">Главная</a>
          
          
              <a class="navbar-brand" href="/albums">Галерея</a>
           
          
              <a class="navbar-brand" href=<%=events_path%>>Ближайшие события</a>
        
           
              <a class="navbar-brand" href=<%=posts_path%>>Блог</a>
         
           
              <a class="navbar-brand" href="/contacts">Контакты</a>
               
              <%if user_signed_in?%>
              
                  <a class="navbar-brand">Привет, <%=current_user.username%></a>
                 
                  
                   <small ><%= link_to 'Выйти?', destroy_user_session_path, :method => :delete %></small>
                   <%else%>

            
                  <a class="navbar-brand" href=<%=new_user_session_path%>>Авторизоваться</a>
               

                  <%end%>

            

                </ul>
              </ul>
              </div>
              </nav>
 
           
               </div>
       
        
             </div>


    
          </div>

        </div>
      </div>
    </nav>


     <!-- Page Header -->

    <header class="masthead" style="background-image: url('<%=@bckg%>')">
      <div class="overlay"></div>
      <div class="container">

        
          <!--visible-sx button navigation-->


      

          <div class="row">
            <div class="visible-xs col-md-3 col-sx-3" >
              <style>
            
            .dropdown-menu {background-color: transparent;}
            </style>

  
           <!--ckeditor-->

           <script src="https://cdn.ckeditor.com/4.10.1/standard/ckeditor.js"></script>       
         

 <div class="clearfix">

  <div class="dropdown">
                  <button class=" btn btn-outline-light dropdown-toggle float-left" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Перейти
                   </button>


                 <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href=<%=main_index_path%>><button type="button" class="btn btn-outline-light">Главная</button></a>
                    <a class="dropdown-item" href=<%=albums_path%>><button type="button" class="btn btn-outline-light">Галерея</button></a>
                    <a class="dropdown-item" href=<%=events_path%>><button type="button" class="btn btn-outline-light">Ближайшие события</button></a>

                    <a class="dropdown-item" href=<%=posts_path%>><button type="button" class="btn btn-outline-light">Блог</button></a>

                    <a class="dropdown-item" href="/contacts"><button type="button" class="btn btn-outline-light">Контакты</button></a>



                  </div>
               
        </div>

       




         
          

          <%if user_signed_in?%>
            <div class="dropdown">
             <button class=" btn btn-outline-light dropdown-toggle float-right" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%=current_user.username%>
                   </button>


                 <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" ><button type="button" class="btn btn-outline-light float-right"><%= link_to 'Выйти?', destroy_user_session_path, :method => :delete %></button></a>
              </div>
              </div>

            <%else%>


            <a class="btn btn-outline-light float-right" href=<%=new_user_session_path%>>Авторизоваться</a>


            <%end%>

            
            </div>
         </div>  

  </div>
</div>  





   </div> 
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1><%=@title%></h1>
              <span class="subheading"><%=@label%></span>
            </div>
          </div>
        </div>

      </div>
    </header>





<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>



    <%= yield %>


    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Your Website 2018</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>


<!-- Bootstrap core JavaScript -->
    <script src="/vendor/jquery/jquery.min.js"></script>
    <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="/js/clean-blog.js"></script>
    <script src="/js/lightgallery-all.min.js"></script>
    <!--tabs-->
    <script src="/js/tabs.js"></script>

   
 <!--simple_format-->
    <script src="/js/simpleformat.js"></script>  


  <script>

   CKEDITOR.editorConfig = function( config )
{
   // misc options
   config.height = '500px';
};

</script>